# application.yml
# 使用.yml时，属性名的值和冒号中间必须有空格，要注意縮進
# 其实yml文件，后面是会被翻译成.properties文件的。
server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/sqltest?useSSL=false&useUnicode=true&characterEncoding=utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root1234

        tomcat:
          max-idle: 10
          min-idle: 5
          max-wait: 10000
          validation-query: SELECT 1
          test-on-borrow: true
          test-while-idle: true
          time-between-eviction-runs-millis: 18800


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: cn.cst.sprinbootstart